server:
  port: 9897

spring:
  application:
    name: spring-boot-mail-gmail

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #MySQL Configuration
  datasource:
    url: jdbc:mysql://localhost:3307/microservices
    username: ${MYSQL_USER:nirmala}
    password: ${MYSQL_PASSWORD:nirmala@123}

    # HikariCP Connection Pool Configuration
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  #JPA Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # Gmail Properties
  mail:
    default-encoding: 'UTF-8'
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Logging Configuration
logging:
  level:
    #org.springframework.security: DEBUG
    com.sahu.mailservice: DEBUG

# Swagger Configuration
springdoc:
  swagger-ui:
    path: /documentation
  api-docs:
    path: /api-docs

openapi:
  title: 🚀 Spring Boot Email Integration with Gmail
  description: A Spring Boot application demonstrating email sending functionality using Gmail's SMTP server. This application showcases how to configure and send emails programmatically using Spring Boot and JavaMailSender.
  version: 1.0.0
  contact:
    name: Nirmala Sahu
    email: nirmalakumarsahu7@gmail.com
    url: https://nirmalakumarsahu.in
  servers:
    - name: dev
      url: http://localhost:9897
      description: Local Development URL

